// Generated by the protocol buffer compiler.  DO NOT EDIT!

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "SystemSettings.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace {

const ::google::protobuf::Descriptor* SystemSettings_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  SystemSettings_reflection_ = NULL;
const ::google::protobuf::Descriptor* SystemSettings_HSV_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  SystemSettings_HSV_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_SystemSettings_2eproto() {
  protobuf_AddDesc_SystemSettings_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "SystemSettings.proto");
  GOOGLE_CHECK(file != NULL);
  SystemSettings_descriptor_ = file->message_type(0);
  static const int SystemSettings_offsets_[37] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SystemSettings, input_edit_camera_setting_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SystemSettings, input_white_balance_blue_u_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SystemSettings, input_white_balance_red_v_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SystemSettings, input_exposure_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SystemSettings, input_brightness_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SystemSettings, input_sharpness_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SystemSettings, input_gain_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SystemSettings, input_hue_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SystemSettings, input_sat_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SystemSettings, input_contrast_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SystemSettings, input_network_ip_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SystemSettings, input_network_port_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SystemSettings, filters_crop_photo_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SystemSettings, filters_crop_firstpoint_x_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SystemSettings, filters_crop_firstpoint_y_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SystemSettings, filters_crop_secondpoint_x_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SystemSettings, filters_crop_secondpoint_y_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SystemSettings, filters_median_blur_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SystemSettings, filters_median_blur_kernelsize_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SystemSettings, filters_adaptive_threshold_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SystemSettings, filters_adaptive_threshold_blocksize_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SystemSettings, filters_adaptive_threshold_c_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SystemSettings, filters_threshold_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SystemSettings, filters_threshold_value_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SystemSettings, filters_dilate_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SystemSettings, filters_dilationsize_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SystemSettings, filters_canny_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SystemSettings, filters_canny_first_threshold_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SystemSettings, filters_canny_second_threshold_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SystemSettings, filters_canny_aperturesize_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SystemSettings, red_instances_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SystemSettings, blue_instances_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SystemSettings, green_instances_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SystemSettings, yellow_instances_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SystemSettings, violet_instances_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SystemSettings, cyan_instances_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SystemSettings, black_instances_),
  };
  SystemSettings_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      SystemSettings_descriptor_,
      SystemSettings::default_instance_,
      SystemSettings_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SystemSettings, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SystemSettings, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(SystemSettings));
  SystemSettings_HSV_descriptor_ = SystemSettings_descriptor_->nested_type(0);
  static const int SystemSettings_HSV_offsets_[3] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SystemSettings_HSV, hue_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SystemSettings_HSV, sat_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SystemSettings_HSV, val_),
  };
  SystemSettings_HSV_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      SystemSettings_HSV_descriptor_,
      SystemSettings_HSV::default_instance_,
      SystemSettings_HSV_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SystemSettings_HSV, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SystemSettings_HSV, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(SystemSettings_HSV));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_SystemSettings_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    SystemSettings_descriptor_, &SystemSettings::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    SystemSettings_HSV_descriptor_, &SystemSettings_HSV::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_SystemSettings_2eproto() {
  delete SystemSettings::default_instance_;
  delete SystemSettings_reflection_;
  delete SystemSettings_HSV::default_instance_;
  delete SystemSettings_HSV_reflection_;
}

void protobuf_AddDesc_SystemSettings_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\024SystemSettings.proto\"\236\n\n\016SystemSetting"
    "s\022!\n\031input_edit_camera_setting\030\001 \002(\010\022\"\n\032"
    "input_WHITE_BALANCE_BLUE_U\030\002 \002(\003\022!\n\031inpu"
    "t_WHITE_BALANCE_RED_V\030\003 \002(\003\022\026\n\016input_EXP"
    "OSURE\030\004 \002(\003\022\030\n\020input_BRIGHTNESS\030\005 \002(\003\022\027\n"
    "\017input_SHARPNESS\030\006 \002(\005\022\022\n\ninput_GAIN\030\007 \002"
    "(\003\022\021\n\tinput_HUE\030\010 \002(\003\022\021\n\tinput_SAT\030\t \002(\003"
    "\022\026\n\016input_CONTRAST\030\n \002(\003\022\030\n\020input_networ"
    "k_ip\030\013 \002(\t\022\032\n\022input_network_port\030\014 \002(\t\022\032"
    "\n\022filters_crop_photo\030\r \002(\010\022!\n\031filters_cr"
    "op_firstPoint_x\030\016 \002(\t\022!\n\031filters_crop_fi"
    "rstPoint_y\030\017 \002(\t\022\"\n\032filters_crop_secondP"
    "oint_x\030\020 \002(\t\022\"\n\032filters_crop_secondPoint"
    "_y\030\021 \002(\t\022\033\n\023filters_median_blur\030\022 \002(\010\022&\n"
    "\036filters_median_blur_kernelSize\030\023 \002(\t\022\"\n"
    "\032filters_Adaptive_threshold\030\024 \002(\010\022,\n$fil"
    "ters_Adaptive_threshold_blockSize\030\025 \002(\003\022"
    "$\n\034filters_Adaptive_threshold_C\030\026 \002(\003\022\031\n"
    "\021filters_Threshold\030\027 \002(\010\022\037\n\027filters_Thre"
    "shold_value\030\030 \002(\003\022\026\n\016filters_dilate\030\031 \002("
    "\010\022\034\n\024filters_dilationSize\030\032 \002(\t\022\025\n\rfilte"
    "rs_Canny\030\033 \002(\010\022%\n\035filters_Canny_First_Th"
    "reshold\030\034 \002(\003\022&\n\036filters_Canny_Second_Th"
    "reshold\030\035 \002(\003\022\"\n\032filters_Canny_apertureS"
    "ize\030\036 \002(\t\022*\n\rred_instances\030\037 \003(\0132\023.Syste"
    "mSettings.HSV\022+\n\016blue_instances\030  \003(\0132\023."
    "SystemSettings.HSV\022,\n\017green_instances\030! "
    "\003(\0132\023.SystemSettings.HSV\022-\n\020yellow_insta"
    "nces\030\" \003(\0132\023.SystemSettings.HSV\022-\n\020viole"
    "t_instances\030# \003(\0132\023.SystemSettings.HSV\022+"
    "\n\016cyan_instances\030$ \003(\0132\023.SystemSettings."
    "HSV\022,\n\017black_instances\030% \003(\0132\023.SystemSet"
    "tings.HSV\032,\n\003HSV\022\013\n\003hue\030\001 \002(\002\022\013\n\003sat\030\002 \002"
    "(\002\022\013\n\003val\030\003 \002(\002", 1335);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "SystemSettings.proto", &protobuf_RegisterTypes);
  SystemSettings::default_instance_ = new SystemSettings();
  SystemSettings_HSV::default_instance_ = new SystemSettings_HSV();
  SystemSettings::default_instance_->InitAsDefaultInstance();
  SystemSettings_HSV::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_SystemSettings_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_SystemSettings_2eproto {
  StaticDescriptorInitializer_SystemSettings_2eproto() {
    protobuf_AddDesc_SystemSettings_2eproto();
  }
} static_descriptor_initializer_SystemSettings_2eproto_;


// ===================================================================

#ifndef _MSC_VER
const int SystemSettings_HSV::kHueFieldNumber;
const int SystemSettings_HSV::kSatFieldNumber;
const int SystemSettings_HSV::kValFieldNumber;
#endif  // !_MSC_VER

SystemSettings_HSV::SystemSettings_HSV()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void SystemSettings_HSV::InitAsDefaultInstance() {
}

SystemSettings_HSV::SystemSettings_HSV(const SystemSettings_HSV& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void SystemSettings_HSV::SharedCtor() {
  _cached_size_ = 0;
  hue_ = 0;
  sat_ = 0;
  val_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

SystemSettings_HSV::~SystemSettings_HSV() {
  SharedDtor();
}

void SystemSettings_HSV::SharedDtor() {
  if (this != default_instance_) {
  }
}

void SystemSettings_HSV::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* SystemSettings_HSV::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return SystemSettings_HSV_descriptor_;
}

const SystemSettings_HSV& SystemSettings_HSV::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_SystemSettings_2eproto();  return *default_instance_;
}

SystemSettings_HSV* SystemSettings_HSV::default_instance_ = NULL;

SystemSettings_HSV* SystemSettings_HSV::New() const {
  return new SystemSettings_HSV;
}

void SystemSettings_HSV::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    hue_ = 0;
    sat_ = 0;
    val_ = 0;
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool SystemSettings_HSV::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required float hue = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_FIXED32) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &hue_)));
          set_has_hue();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(21)) goto parse_sat;
        break;
      }
      
      // required float sat = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_FIXED32) {
         parse_sat:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &sat_)));
          set_has_sat();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(29)) goto parse_val;
        break;
      }
      
      // required float val = 3;
      case 3: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_FIXED32) {
         parse_val:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &val_)));
          set_has_val();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }
      
      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void SystemSettings_HSV::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // required float hue = 1;
  if (has_hue()) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(1, this->hue(), output);
  }
  
  // required float sat = 2;
  if (has_sat()) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(2, this->sat(), output);
  }
  
  // required float val = 3;
  if (has_val()) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(3, this->val(), output);
  }
  
  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* SystemSettings_HSV::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // required float hue = 1;
  if (has_hue()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(1, this->hue(), target);
  }
  
  // required float sat = 2;
  if (has_sat()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(2, this->sat(), target);
  }
  
  // required float val = 3;
  if (has_val()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(3, this->val(), target);
  }
  
  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int SystemSettings_HSV::ByteSize() const {
  int total_size = 0;
  
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required float hue = 1;
    if (has_hue()) {
      total_size += 1 + 4;
    }
    
    // required float sat = 2;
    if (has_sat()) {
      total_size += 1 + 4;
    }
    
    // required float val = 3;
    if (has_val()) {
      total_size += 1 + 4;
    }
    
  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void SystemSettings_HSV::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const SystemSettings_HSV* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const SystemSettings_HSV*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void SystemSettings_HSV::MergeFrom(const SystemSettings_HSV& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_hue()) {
      set_hue(from.hue());
    }
    if (from.has_sat()) {
      set_sat(from.sat());
    }
    if (from.has_val()) {
      set_val(from.val());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void SystemSettings_HSV::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void SystemSettings_HSV::CopyFrom(const SystemSettings_HSV& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool SystemSettings_HSV::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000007) != 0x00000007) return false;
  
  return true;
}

void SystemSettings_HSV::Swap(SystemSettings_HSV* other) {
  if (other != this) {
    std::swap(hue_, other->hue_);
    std::swap(sat_, other->sat_);
    std::swap(val_, other->val_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata SystemSettings_HSV::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = SystemSettings_HSV_descriptor_;
  metadata.reflection = SystemSettings_HSV_reflection_;
  return metadata;
}


// -------------------------------------------------------------------

#ifndef _MSC_VER
const int SystemSettings::kInputEditCameraSettingFieldNumber;
const int SystemSettings::kInputWHITEBALANCEBLUEUFieldNumber;
const int SystemSettings::kInputWHITEBALANCEREDVFieldNumber;
const int SystemSettings::kInputEXPOSUREFieldNumber;
const int SystemSettings::kInputBRIGHTNESSFieldNumber;
const int SystemSettings::kInputSHARPNESSFieldNumber;
const int SystemSettings::kInputGAINFieldNumber;
const int SystemSettings::kInputHUEFieldNumber;
const int SystemSettings::kInputSATFieldNumber;
const int SystemSettings::kInputCONTRASTFieldNumber;
const int SystemSettings::kInputNetworkIpFieldNumber;
const int SystemSettings::kInputNetworkPortFieldNumber;
const int SystemSettings::kFiltersCropPhotoFieldNumber;
const int SystemSettings::kFiltersCropFirstPointXFieldNumber;
const int SystemSettings::kFiltersCropFirstPointYFieldNumber;
const int SystemSettings::kFiltersCropSecondPointXFieldNumber;
const int SystemSettings::kFiltersCropSecondPointYFieldNumber;
const int SystemSettings::kFiltersMedianBlurFieldNumber;
const int SystemSettings::kFiltersMedianBlurKernelSizeFieldNumber;
const int SystemSettings::kFiltersAdaptiveThresholdFieldNumber;
const int SystemSettings::kFiltersAdaptiveThresholdBlockSizeFieldNumber;
const int SystemSettings::kFiltersAdaptiveThresholdCFieldNumber;
const int SystemSettings::kFiltersThresholdFieldNumber;
const int SystemSettings::kFiltersThresholdValueFieldNumber;
const int SystemSettings::kFiltersDilateFieldNumber;
const int SystemSettings::kFiltersDilationSizeFieldNumber;
const int SystemSettings::kFiltersCannyFieldNumber;
const int SystemSettings::kFiltersCannyFirstThresholdFieldNumber;
const int SystemSettings::kFiltersCannySecondThresholdFieldNumber;
const int SystemSettings::kFiltersCannyApertureSizeFieldNumber;
const int SystemSettings::kRedInstancesFieldNumber;
const int SystemSettings::kBlueInstancesFieldNumber;
const int SystemSettings::kGreenInstancesFieldNumber;
const int SystemSettings::kYellowInstancesFieldNumber;
const int SystemSettings::kVioletInstancesFieldNumber;
const int SystemSettings::kCyanInstancesFieldNumber;
const int SystemSettings::kBlackInstancesFieldNumber;
#endif  // !_MSC_VER

SystemSettings::SystemSettings()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void SystemSettings::InitAsDefaultInstance() {
}

SystemSettings::SystemSettings(const SystemSettings& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void SystemSettings::SharedCtor() {
  _cached_size_ = 0;
  input_edit_camera_setting_ = false;
  input_white_balance_blue_u_ = GOOGLE_LONGLONG(0);
  input_white_balance_red_v_ = GOOGLE_LONGLONG(0);
  input_exposure_ = GOOGLE_LONGLONG(0);
  input_brightness_ = GOOGLE_LONGLONG(0);
  input_sharpness_ = 0;
  input_gain_ = GOOGLE_LONGLONG(0);
  input_hue_ = GOOGLE_LONGLONG(0);
  input_sat_ = GOOGLE_LONGLONG(0);
  input_contrast_ = GOOGLE_LONGLONG(0);
  input_network_ip_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  input_network_port_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  filters_crop_photo_ = false;
  filters_crop_firstpoint_x_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  filters_crop_firstpoint_y_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  filters_crop_secondpoint_x_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  filters_crop_secondpoint_y_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  filters_median_blur_ = false;
  filters_median_blur_kernelsize_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  filters_adaptive_threshold_ = false;
  filters_adaptive_threshold_blocksize_ = GOOGLE_LONGLONG(0);
  filters_adaptive_threshold_c_ = GOOGLE_LONGLONG(0);
  filters_threshold_ = false;
  filters_threshold_value_ = GOOGLE_LONGLONG(0);
  filters_dilate_ = false;
  filters_dilationsize_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  filters_canny_ = false;
  filters_canny_first_threshold_ = GOOGLE_LONGLONG(0);
  filters_canny_second_threshold_ = GOOGLE_LONGLONG(0);
  filters_canny_aperturesize_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

SystemSettings::~SystemSettings() {
  SharedDtor();
}

void SystemSettings::SharedDtor() {
  if (input_network_ip_ != &::google::protobuf::internal::kEmptyString) {
    delete input_network_ip_;
  }
  if (input_network_port_ != &::google::protobuf::internal::kEmptyString) {
    delete input_network_port_;
  }
  if (filters_crop_firstpoint_x_ != &::google::protobuf::internal::kEmptyString) {
    delete filters_crop_firstpoint_x_;
  }
  if (filters_crop_firstpoint_y_ != &::google::protobuf::internal::kEmptyString) {
    delete filters_crop_firstpoint_y_;
  }
  if (filters_crop_secondpoint_x_ != &::google::protobuf::internal::kEmptyString) {
    delete filters_crop_secondpoint_x_;
  }
  if (filters_crop_secondpoint_y_ != &::google::protobuf::internal::kEmptyString) {
    delete filters_crop_secondpoint_y_;
  }
  if (filters_median_blur_kernelsize_ != &::google::protobuf::internal::kEmptyString) {
    delete filters_median_blur_kernelsize_;
  }
  if (filters_dilationsize_ != &::google::protobuf::internal::kEmptyString) {
    delete filters_dilationsize_;
  }
  if (filters_canny_aperturesize_ != &::google::protobuf::internal::kEmptyString) {
    delete filters_canny_aperturesize_;
  }
  if (this != default_instance_) {
  }
}

void SystemSettings::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* SystemSettings::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return SystemSettings_descriptor_;
}

const SystemSettings& SystemSettings::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_SystemSettings_2eproto();  return *default_instance_;
}

SystemSettings* SystemSettings::default_instance_ = NULL;

SystemSettings* SystemSettings::New() const {
  return new SystemSettings;
}

void SystemSettings::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    input_edit_camera_setting_ = false;
    input_white_balance_blue_u_ = GOOGLE_LONGLONG(0);
    input_white_balance_red_v_ = GOOGLE_LONGLONG(0);
    input_exposure_ = GOOGLE_LONGLONG(0);
    input_brightness_ = GOOGLE_LONGLONG(0);
    input_sharpness_ = 0;
    input_gain_ = GOOGLE_LONGLONG(0);
    input_hue_ = GOOGLE_LONGLONG(0);
  }
  if (_has_bits_[8 / 32] & (0xffu << (8 % 32))) {
    input_sat_ = GOOGLE_LONGLONG(0);
    input_contrast_ = GOOGLE_LONGLONG(0);
    if (has_input_network_ip()) {
      if (input_network_ip_ != &::google::protobuf::internal::kEmptyString) {
        input_network_ip_->clear();
      }
    }
    if (has_input_network_port()) {
      if (input_network_port_ != &::google::protobuf::internal::kEmptyString) {
        input_network_port_->clear();
      }
    }
    filters_crop_photo_ = false;
    if (has_filters_crop_firstpoint_x()) {
      if (filters_crop_firstpoint_x_ != &::google::protobuf::internal::kEmptyString) {
        filters_crop_firstpoint_x_->clear();
      }
    }
    if (has_filters_crop_firstpoint_y()) {
      if (filters_crop_firstpoint_y_ != &::google::protobuf::internal::kEmptyString) {
        filters_crop_firstpoint_y_->clear();
      }
    }
    if (has_filters_crop_secondpoint_x()) {
      if (filters_crop_secondpoint_x_ != &::google::protobuf::internal::kEmptyString) {
        filters_crop_secondpoint_x_->clear();
      }
    }
  }
  if (_has_bits_[16 / 32] & (0xffu << (16 % 32))) {
    if (has_filters_crop_secondpoint_y()) {
      if (filters_crop_secondpoint_y_ != &::google::protobuf::internal::kEmptyString) {
        filters_crop_secondpoint_y_->clear();
      }
    }
    filters_median_blur_ = false;
    if (has_filters_median_blur_kernelsize()) {
      if (filters_median_blur_kernelsize_ != &::google::protobuf::internal::kEmptyString) {
        filters_median_blur_kernelsize_->clear();
      }
    }
    filters_adaptive_threshold_ = false;
    filters_adaptive_threshold_blocksize_ = GOOGLE_LONGLONG(0);
    filters_adaptive_threshold_c_ = GOOGLE_LONGLONG(0);
    filters_threshold_ = false;
    filters_threshold_value_ = GOOGLE_LONGLONG(0);
  }
  if (_has_bits_[24 / 32] & (0xffu << (24 % 32))) {
    filters_dilate_ = false;
    if (has_filters_dilationsize()) {
      if (filters_dilationsize_ != &::google::protobuf::internal::kEmptyString) {
        filters_dilationsize_->clear();
      }
    }
    filters_canny_ = false;
    filters_canny_first_threshold_ = GOOGLE_LONGLONG(0);
    filters_canny_second_threshold_ = GOOGLE_LONGLONG(0);
    if (has_filters_canny_aperturesize()) {
      if (filters_canny_aperturesize_ != &::google::protobuf::internal::kEmptyString) {
        filters_canny_aperturesize_->clear();
      }
    }
  }
  red_instances_.Clear();
  blue_instances_.Clear();
  green_instances_.Clear();
  yellow_instances_.Clear();
  violet_instances_.Clear();
  cyan_instances_.Clear();
  black_instances_.Clear();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool SystemSettings::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required bool input_edit_camera_setting = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &input_edit_camera_setting_)));
          set_has_input_edit_camera_setting();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(16)) goto parse_input_WHITE_BALANCE_BLUE_U;
        break;
      }
      
      // required int64 input_WHITE_BALANCE_BLUE_U = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_input_WHITE_BALANCE_BLUE_U:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int64, ::google::protobuf::internal::WireFormatLite::TYPE_INT64>(
                 input, &input_white_balance_blue_u_)));
          set_has_input_white_balance_blue_u();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(24)) goto parse_input_WHITE_BALANCE_RED_V;
        break;
      }
      
      // required int64 input_WHITE_BALANCE_RED_V = 3;
      case 3: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_input_WHITE_BALANCE_RED_V:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int64, ::google::protobuf::internal::WireFormatLite::TYPE_INT64>(
                 input, &input_white_balance_red_v_)));
          set_has_input_white_balance_red_v();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(32)) goto parse_input_EXPOSURE;
        break;
      }
      
      // required int64 input_EXPOSURE = 4;
      case 4: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_input_EXPOSURE:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int64, ::google::protobuf::internal::WireFormatLite::TYPE_INT64>(
                 input, &input_exposure_)));
          set_has_input_exposure();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(40)) goto parse_input_BRIGHTNESS;
        break;
      }
      
      // required int64 input_BRIGHTNESS = 5;
      case 5: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_input_BRIGHTNESS:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int64, ::google::protobuf::internal::WireFormatLite::TYPE_INT64>(
                 input, &input_brightness_)));
          set_has_input_brightness();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(48)) goto parse_input_SHARPNESS;
        break;
      }
      
      // required int32 input_SHARPNESS = 6;
      case 6: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_input_SHARPNESS:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &input_sharpness_)));
          set_has_input_sharpness();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(56)) goto parse_input_GAIN;
        break;
      }
      
      // required int64 input_GAIN = 7;
      case 7: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_input_GAIN:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int64, ::google::protobuf::internal::WireFormatLite::TYPE_INT64>(
                 input, &input_gain_)));
          set_has_input_gain();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(64)) goto parse_input_HUE;
        break;
      }
      
      // required int64 input_HUE = 8;
      case 8: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_input_HUE:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int64, ::google::protobuf::internal::WireFormatLite::TYPE_INT64>(
                 input, &input_hue_)));
          set_has_input_hue();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(72)) goto parse_input_SAT;
        break;
      }
      
      // required int64 input_SAT = 9;
      case 9: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_input_SAT:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int64, ::google::protobuf::internal::WireFormatLite::TYPE_INT64>(
                 input, &input_sat_)));
          set_has_input_sat();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(80)) goto parse_input_CONTRAST;
        break;
      }
      
      // required int64 input_CONTRAST = 10;
      case 10: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_input_CONTRAST:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int64, ::google::protobuf::internal::WireFormatLite::TYPE_INT64>(
                 input, &input_contrast_)));
          set_has_input_contrast();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(90)) goto parse_input_network_ip;
        break;
      }
      
      // required string input_network_ip = 11;
      case 11: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_input_network_ip:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_input_network_ip()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8String(
            this->input_network_ip().data(), this->input_network_ip().length(),
            ::google::protobuf::internal::WireFormat::PARSE);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(98)) goto parse_input_network_port;
        break;
      }
      
      // required string input_network_port = 12;
      case 12: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_input_network_port:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_input_network_port()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8String(
            this->input_network_port().data(), this->input_network_port().length(),
            ::google::protobuf::internal::WireFormat::PARSE);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(104)) goto parse_filters_crop_photo;
        break;
      }
      
      // required bool filters_crop_photo = 13;
      case 13: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_filters_crop_photo:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &filters_crop_photo_)));
          set_has_filters_crop_photo();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(114)) goto parse_filters_crop_firstPoint_x;
        break;
      }
      
      // required string filters_crop_firstPoint_x = 14;
      case 14: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_filters_crop_firstPoint_x:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_filters_crop_firstpoint_x()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8String(
            this->filters_crop_firstpoint_x().data(), this->filters_crop_firstpoint_x().length(),
            ::google::protobuf::internal::WireFormat::PARSE);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(122)) goto parse_filters_crop_firstPoint_y;
        break;
      }
      
      // required string filters_crop_firstPoint_y = 15;
      case 15: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_filters_crop_firstPoint_y:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_filters_crop_firstpoint_y()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8String(
            this->filters_crop_firstpoint_y().data(), this->filters_crop_firstpoint_y().length(),
            ::google::protobuf::internal::WireFormat::PARSE);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(130)) goto parse_filters_crop_secondPoint_x;
        break;
      }
      
      // required string filters_crop_secondPoint_x = 16;
      case 16: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_filters_crop_secondPoint_x:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_filters_crop_secondpoint_x()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8String(
            this->filters_crop_secondpoint_x().data(), this->filters_crop_secondpoint_x().length(),
            ::google::protobuf::internal::WireFormat::PARSE);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(138)) goto parse_filters_crop_secondPoint_y;
        break;
      }
      
      // required string filters_crop_secondPoint_y = 17;
      case 17: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_filters_crop_secondPoint_y:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_filters_crop_secondpoint_y()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8String(
            this->filters_crop_secondpoint_y().data(), this->filters_crop_secondpoint_y().length(),
            ::google::protobuf::internal::WireFormat::PARSE);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(144)) goto parse_filters_median_blur;
        break;
      }
      
      // required bool filters_median_blur = 18;
      case 18: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_filters_median_blur:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &filters_median_blur_)));
          set_has_filters_median_blur();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(154)) goto parse_filters_median_blur_kernelSize;
        break;
      }
      
      // required string filters_median_blur_kernelSize = 19;
      case 19: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_filters_median_blur_kernelSize:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_filters_median_blur_kernelsize()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8String(
            this->filters_median_blur_kernelsize().data(), this->filters_median_blur_kernelsize().length(),
            ::google::protobuf::internal::WireFormat::PARSE);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(160)) goto parse_filters_Adaptive_threshold;
        break;
      }
      
      // required bool filters_Adaptive_threshold = 20;
      case 20: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_filters_Adaptive_threshold:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &filters_adaptive_threshold_)));
          set_has_filters_adaptive_threshold();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(168)) goto parse_filters_Adaptive_threshold_blockSize;
        break;
      }
      
      // required int64 filters_Adaptive_threshold_blockSize = 21;
      case 21: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_filters_Adaptive_threshold_blockSize:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int64, ::google::protobuf::internal::WireFormatLite::TYPE_INT64>(
                 input, &filters_adaptive_threshold_blocksize_)));
          set_has_filters_adaptive_threshold_blocksize();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(176)) goto parse_filters_Adaptive_threshold_C;
        break;
      }
      
      // required int64 filters_Adaptive_threshold_C = 22;
      case 22: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_filters_Adaptive_threshold_C:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int64, ::google::protobuf::internal::WireFormatLite::TYPE_INT64>(
                 input, &filters_adaptive_threshold_c_)));
          set_has_filters_adaptive_threshold_c();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(184)) goto parse_filters_Threshold;
        break;
      }
      
      // required bool filters_Threshold = 23;
      case 23: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_filters_Threshold:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &filters_threshold_)));
          set_has_filters_threshold();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(192)) goto parse_filters_Threshold_value;
        break;
      }
      
      // required int64 filters_Threshold_value = 24;
      case 24: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_filters_Threshold_value:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int64, ::google::protobuf::internal::WireFormatLite::TYPE_INT64>(
                 input, &filters_threshold_value_)));
          set_has_filters_threshold_value();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(200)) goto parse_filters_dilate;
        break;
      }
      
      // required bool filters_dilate = 25;
      case 25: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_filters_dilate:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &filters_dilate_)));
          set_has_filters_dilate();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(210)) goto parse_filters_dilationSize;
        break;
      }
      
      // required string filters_dilationSize = 26;
      case 26: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_filters_dilationSize:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_filters_dilationsize()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8String(
            this->filters_dilationsize().data(), this->filters_dilationsize().length(),
            ::google::protobuf::internal::WireFormat::PARSE);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(216)) goto parse_filters_Canny;
        break;
      }
      
      // required bool filters_Canny = 27;
      case 27: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_filters_Canny:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &filters_canny_)));
          set_has_filters_canny();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(224)) goto parse_filters_Canny_First_Threshold;
        break;
      }
      
      // required int64 filters_Canny_First_Threshold = 28;
      case 28: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_filters_Canny_First_Threshold:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int64, ::google::protobuf::internal::WireFormatLite::TYPE_INT64>(
                 input, &filters_canny_first_threshold_)));
          set_has_filters_canny_first_threshold();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(232)) goto parse_filters_Canny_Second_Threshold;
        break;
      }
      
      // required int64 filters_Canny_Second_Threshold = 29;
      case 29: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_filters_Canny_Second_Threshold:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int64, ::google::protobuf::internal::WireFormatLite::TYPE_INT64>(
                 input, &filters_canny_second_threshold_)));
          set_has_filters_canny_second_threshold();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(242)) goto parse_filters_Canny_apertureSize;
        break;
      }
      
      // required string filters_Canny_apertureSize = 30;
      case 30: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_filters_Canny_apertureSize:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_filters_canny_aperturesize()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8String(
            this->filters_canny_aperturesize().data(), this->filters_canny_aperturesize().length(),
            ::google::protobuf::internal::WireFormat::PARSE);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(250)) goto parse_red_instances;
        break;
      }
      
      // repeated .SystemSettings.HSV red_instances = 31;
      case 31: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_red_instances:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
                input, add_red_instances()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(250)) goto parse_red_instances;
        if (input->ExpectTag(258)) goto parse_blue_instances;
        break;
      }
      
      // repeated .SystemSettings.HSV blue_instances = 32;
      case 32: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_blue_instances:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
                input, add_blue_instances()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(258)) goto parse_blue_instances;
        if (input->ExpectTag(266)) goto parse_green_instances;
        break;
      }
      
      // repeated .SystemSettings.HSV green_instances = 33;
      case 33: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_green_instances:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
                input, add_green_instances()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(266)) goto parse_green_instances;
        if (input->ExpectTag(274)) goto parse_yellow_instances;
        break;
      }
      
      // repeated .SystemSettings.HSV yellow_instances = 34;
      case 34: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_yellow_instances:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
                input, add_yellow_instances()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(274)) goto parse_yellow_instances;
        if (input->ExpectTag(282)) goto parse_violet_instances;
        break;
      }
      
      // repeated .SystemSettings.HSV violet_instances = 35;
      case 35: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_violet_instances:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
                input, add_violet_instances()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(282)) goto parse_violet_instances;
        if (input->ExpectTag(290)) goto parse_cyan_instances;
        break;
      }
      
      // repeated .SystemSettings.HSV cyan_instances = 36;
      case 36: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_cyan_instances:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
                input, add_cyan_instances()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(290)) goto parse_cyan_instances;
        if (input->ExpectTag(298)) goto parse_black_instances;
        break;
      }
      
      // repeated .SystemSettings.HSV black_instances = 37;
      case 37: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_black_instances:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
                input, add_black_instances()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(298)) goto parse_black_instances;
        if (input->ExpectAtEnd()) return true;
        break;
      }
      
      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void SystemSettings::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // required bool input_edit_camera_setting = 1;
  if (has_input_edit_camera_setting()) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(1, this->input_edit_camera_setting(), output);
  }
  
  // required int64 input_WHITE_BALANCE_BLUE_U = 2;
  if (has_input_white_balance_blue_u()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt64(2, this->input_white_balance_blue_u(), output);
  }
  
  // required int64 input_WHITE_BALANCE_RED_V = 3;
  if (has_input_white_balance_red_v()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt64(3, this->input_white_balance_red_v(), output);
  }
  
  // required int64 input_EXPOSURE = 4;
  if (has_input_exposure()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt64(4, this->input_exposure(), output);
  }
  
  // required int64 input_BRIGHTNESS = 5;
  if (has_input_brightness()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt64(5, this->input_brightness(), output);
  }
  
  // required int32 input_SHARPNESS = 6;
  if (has_input_sharpness()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(6, this->input_sharpness(), output);
  }
  
  // required int64 input_GAIN = 7;
  if (has_input_gain()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt64(7, this->input_gain(), output);
  }
  
  // required int64 input_HUE = 8;
  if (has_input_hue()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt64(8, this->input_hue(), output);
  }
  
  // required int64 input_SAT = 9;
  if (has_input_sat()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt64(9, this->input_sat(), output);
  }
  
  // required int64 input_CONTRAST = 10;
  if (has_input_contrast()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt64(10, this->input_contrast(), output);
  }
  
  // required string input_network_ip = 11;
  if (has_input_network_ip()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->input_network_ip().data(), this->input_network_ip().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    ::google::protobuf::internal::WireFormatLite::WriteString(
      11, this->input_network_ip(), output);
  }
  
  // required string input_network_port = 12;
  if (has_input_network_port()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->input_network_port().data(), this->input_network_port().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    ::google::protobuf::internal::WireFormatLite::WriteString(
      12, this->input_network_port(), output);
  }
  
  // required bool filters_crop_photo = 13;
  if (has_filters_crop_photo()) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(13, this->filters_crop_photo(), output);
  }
  
  // required string filters_crop_firstPoint_x = 14;
  if (has_filters_crop_firstpoint_x()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->filters_crop_firstpoint_x().data(), this->filters_crop_firstpoint_x().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    ::google::protobuf::internal::WireFormatLite::WriteString(
      14, this->filters_crop_firstpoint_x(), output);
  }
  
  // required string filters_crop_firstPoint_y = 15;
  if (has_filters_crop_firstpoint_y()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->filters_crop_firstpoint_y().data(), this->filters_crop_firstpoint_y().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    ::google::protobuf::internal::WireFormatLite::WriteString(
      15, this->filters_crop_firstpoint_y(), output);
  }
  
  // required string filters_crop_secondPoint_x = 16;
  if (has_filters_crop_secondpoint_x()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->filters_crop_secondpoint_x().data(), this->filters_crop_secondpoint_x().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    ::google::protobuf::internal::WireFormatLite::WriteString(
      16, this->filters_crop_secondpoint_x(), output);
  }
  
  // required string filters_crop_secondPoint_y = 17;
  if (has_filters_crop_secondpoint_y()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->filters_crop_secondpoint_y().data(), this->filters_crop_secondpoint_y().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    ::google::protobuf::internal::WireFormatLite::WriteString(
      17, this->filters_crop_secondpoint_y(), output);
  }
  
  // required bool filters_median_blur = 18;
  if (has_filters_median_blur()) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(18, this->filters_median_blur(), output);
  }
  
  // required string filters_median_blur_kernelSize = 19;
  if (has_filters_median_blur_kernelsize()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->filters_median_blur_kernelsize().data(), this->filters_median_blur_kernelsize().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    ::google::protobuf::internal::WireFormatLite::WriteString(
      19, this->filters_median_blur_kernelsize(), output);
  }
  
  // required bool filters_Adaptive_threshold = 20;
  if (has_filters_adaptive_threshold()) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(20, this->filters_adaptive_threshold(), output);
  }
  
  // required int64 filters_Adaptive_threshold_blockSize = 21;
  if (has_filters_adaptive_threshold_blocksize()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt64(21, this->filters_adaptive_threshold_blocksize(), output);
  }
  
  // required int64 filters_Adaptive_threshold_C = 22;
  if (has_filters_adaptive_threshold_c()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt64(22, this->filters_adaptive_threshold_c(), output);
  }
  
  // required bool filters_Threshold = 23;
  if (has_filters_threshold()) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(23, this->filters_threshold(), output);
  }
  
  // required int64 filters_Threshold_value = 24;
  if (has_filters_threshold_value()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt64(24, this->filters_threshold_value(), output);
  }
  
  // required bool filters_dilate = 25;
  if (has_filters_dilate()) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(25, this->filters_dilate(), output);
  }
  
  // required string filters_dilationSize = 26;
  if (has_filters_dilationsize()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->filters_dilationsize().data(), this->filters_dilationsize().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    ::google::protobuf::internal::WireFormatLite::WriteString(
      26, this->filters_dilationsize(), output);
  }
  
  // required bool filters_Canny = 27;
  if (has_filters_canny()) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(27, this->filters_canny(), output);
  }
  
  // required int64 filters_Canny_First_Threshold = 28;
  if (has_filters_canny_first_threshold()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt64(28, this->filters_canny_first_threshold(), output);
  }
  
  // required int64 filters_Canny_Second_Threshold = 29;
  if (has_filters_canny_second_threshold()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt64(29, this->filters_canny_second_threshold(), output);
  }
  
  // required string filters_Canny_apertureSize = 30;
  if (has_filters_canny_aperturesize()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->filters_canny_aperturesize().data(), this->filters_canny_aperturesize().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    ::google::protobuf::internal::WireFormatLite::WriteString(
      30, this->filters_canny_aperturesize(), output);
  }
  
  // repeated .SystemSettings.HSV red_instances = 31;
  for (int i = 0; i < this->red_instances_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      31, this->red_instances(i), output);
  }
  
  // repeated .SystemSettings.HSV blue_instances = 32;
  for (int i = 0; i < this->blue_instances_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      32, this->blue_instances(i), output);
  }
  
  // repeated .SystemSettings.HSV green_instances = 33;
  for (int i = 0; i < this->green_instances_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      33, this->green_instances(i), output);
  }
  
  // repeated .SystemSettings.HSV yellow_instances = 34;
  for (int i = 0; i < this->yellow_instances_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      34, this->yellow_instances(i), output);
  }
  
  // repeated .SystemSettings.HSV violet_instances = 35;
  for (int i = 0; i < this->violet_instances_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      35, this->violet_instances(i), output);
  }
  
  // repeated .SystemSettings.HSV cyan_instances = 36;
  for (int i = 0; i < this->cyan_instances_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      36, this->cyan_instances(i), output);
  }
  
  // repeated .SystemSettings.HSV black_instances = 37;
  for (int i = 0; i < this->black_instances_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      37, this->black_instances(i), output);
  }
  
  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* SystemSettings::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // required bool input_edit_camera_setting = 1;
  if (has_input_edit_camera_setting()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(1, this->input_edit_camera_setting(), target);
  }
  
  // required int64 input_WHITE_BALANCE_BLUE_U = 2;
  if (has_input_white_balance_blue_u()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt64ToArray(2, this->input_white_balance_blue_u(), target);
  }
  
  // required int64 input_WHITE_BALANCE_RED_V = 3;
  if (has_input_white_balance_red_v()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt64ToArray(3, this->input_white_balance_red_v(), target);
  }
  
  // required int64 input_EXPOSURE = 4;
  if (has_input_exposure()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt64ToArray(4, this->input_exposure(), target);
  }
  
  // required int64 input_BRIGHTNESS = 5;
  if (has_input_brightness()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt64ToArray(5, this->input_brightness(), target);
  }
  
  // required int32 input_SHARPNESS = 6;
  if (has_input_sharpness()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(6, this->input_sharpness(), target);
  }
  
  // required int64 input_GAIN = 7;
  if (has_input_gain()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt64ToArray(7, this->input_gain(), target);
  }
  
  // required int64 input_HUE = 8;
  if (has_input_hue()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt64ToArray(8, this->input_hue(), target);
  }
  
  // required int64 input_SAT = 9;
  if (has_input_sat()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt64ToArray(9, this->input_sat(), target);
  }
  
  // required int64 input_CONTRAST = 10;
  if (has_input_contrast()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt64ToArray(10, this->input_contrast(), target);
  }
  
  // required string input_network_ip = 11;
  if (has_input_network_ip()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->input_network_ip().data(), this->input_network_ip().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        11, this->input_network_ip(), target);
  }
  
  // required string input_network_port = 12;
  if (has_input_network_port()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->input_network_port().data(), this->input_network_port().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        12, this->input_network_port(), target);
  }
  
  // required bool filters_crop_photo = 13;
  if (has_filters_crop_photo()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(13, this->filters_crop_photo(), target);
  }
  
  // required string filters_crop_firstPoint_x = 14;
  if (has_filters_crop_firstpoint_x()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->filters_crop_firstpoint_x().data(), this->filters_crop_firstpoint_x().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        14, this->filters_crop_firstpoint_x(), target);
  }
  
  // required string filters_crop_firstPoint_y = 15;
  if (has_filters_crop_firstpoint_y()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->filters_crop_firstpoint_y().data(), this->filters_crop_firstpoint_y().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        15, this->filters_crop_firstpoint_y(), target);
  }
  
  // required string filters_crop_secondPoint_x = 16;
  if (has_filters_crop_secondpoint_x()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->filters_crop_secondpoint_x().data(), this->filters_crop_secondpoint_x().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        16, this->filters_crop_secondpoint_x(), target);
  }
  
  // required string filters_crop_secondPoint_y = 17;
  if (has_filters_crop_secondpoint_y()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->filters_crop_secondpoint_y().data(), this->filters_crop_secondpoint_y().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        17, this->filters_crop_secondpoint_y(), target);
  }
  
  // required bool filters_median_blur = 18;
  if (has_filters_median_blur()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(18, this->filters_median_blur(), target);
  }
  
  // required string filters_median_blur_kernelSize = 19;
  if (has_filters_median_blur_kernelsize()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->filters_median_blur_kernelsize().data(), this->filters_median_blur_kernelsize().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        19, this->filters_median_blur_kernelsize(), target);
  }
  
  // required bool filters_Adaptive_threshold = 20;
  if (has_filters_adaptive_threshold()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(20, this->filters_adaptive_threshold(), target);
  }
  
  // required int64 filters_Adaptive_threshold_blockSize = 21;
  if (has_filters_adaptive_threshold_blocksize()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt64ToArray(21, this->filters_adaptive_threshold_blocksize(), target);
  }
  
  // required int64 filters_Adaptive_threshold_C = 22;
  if (has_filters_adaptive_threshold_c()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt64ToArray(22, this->filters_adaptive_threshold_c(), target);
  }
  
  // required bool filters_Threshold = 23;
  if (has_filters_threshold()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(23, this->filters_threshold(), target);
  }
  
  // required int64 filters_Threshold_value = 24;
  if (has_filters_threshold_value()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt64ToArray(24, this->filters_threshold_value(), target);
  }
  
  // required bool filters_dilate = 25;
  if (has_filters_dilate()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(25, this->filters_dilate(), target);
  }
  
  // required string filters_dilationSize = 26;
  if (has_filters_dilationsize()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->filters_dilationsize().data(), this->filters_dilationsize().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        26, this->filters_dilationsize(), target);
  }
  
  // required bool filters_Canny = 27;
  if (has_filters_canny()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(27, this->filters_canny(), target);
  }
  
  // required int64 filters_Canny_First_Threshold = 28;
  if (has_filters_canny_first_threshold()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt64ToArray(28, this->filters_canny_first_threshold(), target);
  }
  
  // required int64 filters_Canny_Second_Threshold = 29;
  if (has_filters_canny_second_threshold()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt64ToArray(29, this->filters_canny_second_threshold(), target);
  }
  
  // required string filters_Canny_apertureSize = 30;
  if (has_filters_canny_aperturesize()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->filters_canny_aperturesize().data(), this->filters_canny_aperturesize().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        30, this->filters_canny_aperturesize(), target);
  }
  
  // repeated .SystemSettings.HSV red_instances = 31;
  for (int i = 0; i < this->red_instances_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        31, this->red_instances(i), target);
  }
  
  // repeated .SystemSettings.HSV blue_instances = 32;
  for (int i = 0; i < this->blue_instances_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        32, this->blue_instances(i), target);
  }
  
  // repeated .SystemSettings.HSV green_instances = 33;
  for (int i = 0; i < this->green_instances_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        33, this->green_instances(i), target);
  }
  
  // repeated .SystemSettings.HSV yellow_instances = 34;
  for (int i = 0; i < this->yellow_instances_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        34, this->yellow_instances(i), target);
  }
  
  // repeated .SystemSettings.HSV violet_instances = 35;
  for (int i = 0; i < this->violet_instances_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        35, this->violet_instances(i), target);
  }
  
  // repeated .SystemSettings.HSV cyan_instances = 36;
  for (int i = 0; i < this->cyan_instances_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        36, this->cyan_instances(i), target);
  }
  
  // repeated .SystemSettings.HSV black_instances = 37;
  for (int i = 0; i < this->black_instances_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        37, this->black_instances(i), target);
  }
  
  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int SystemSettings::ByteSize() const {
  int total_size = 0;
  
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required bool input_edit_camera_setting = 1;
    if (has_input_edit_camera_setting()) {
      total_size += 1 + 1;
    }
    
    // required int64 input_WHITE_BALANCE_BLUE_U = 2;
    if (has_input_white_balance_blue_u()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int64Size(
          this->input_white_balance_blue_u());
    }
    
    // required int64 input_WHITE_BALANCE_RED_V = 3;
    if (has_input_white_balance_red_v()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int64Size(
          this->input_white_balance_red_v());
    }
    
    // required int64 input_EXPOSURE = 4;
    if (has_input_exposure()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int64Size(
          this->input_exposure());
    }
    
    // required int64 input_BRIGHTNESS = 5;
    if (has_input_brightness()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int64Size(
          this->input_brightness());
    }
    
    // required int32 input_SHARPNESS = 6;
    if (has_input_sharpness()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->input_sharpness());
    }
    
    // required int64 input_GAIN = 7;
    if (has_input_gain()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int64Size(
          this->input_gain());
    }
    
    // required int64 input_HUE = 8;
    if (has_input_hue()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int64Size(
          this->input_hue());
    }
    
  }
  if (_has_bits_[8 / 32] & (0xffu << (8 % 32))) {
    // required int64 input_SAT = 9;
    if (has_input_sat()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int64Size(
          this->input_sat());
    }
    
    // required int64 input_CONTRAST = 10;
    if (has_input_contrast()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int64Size(
          this->input_contrast());
    }
    
    // required string input_network_ip = 11;
    if (has_input_network_ip()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->input_network_ip());
    }
    
    // required string input_network_port = 12;
    if (has_input_network_port()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->input_network_port());
    }
    
    // required bool filters_crop_photo = 13;
    if (has_filters_crop_photo()) {
      total_size += 1 + 1;
    }
    
    // required string filters_crop_firstPoint_x = 14;
    if (has_filters_crop_firstpoint_x()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->filters_crop_firstpoint_x());
    }
    
    // required string filters_crop_firstPoint_y = 15;
    if (has_filters_crop_firstpoint_y()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->filters_crop_firstpoint_y());
    }
    
    // required string filters_crop_secondPoint_x = 16;
    if (has_filters_crop_secondpoint_x()) {
      total_size += 2 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->filters_crop_secondpoint_x());
    }
    
  }
  if (_has_bits_[16 / 32] & (0xffu << (16 % 32))) {
    // required string filters_crop_secondPoint_y = 17;
    if (has_filters_crop_secondpoint_y()) {
      total_size += 2 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->filters_crop_secondpoint_y());
    }
    
    // required bool filters_median_blur = 18;
    if (has_filters_median_blur()) {
      total_size += 2 + 1;
    }
    
    // required string filters_median_blur_kernelSize = 19;
    if (has_filters_median_blur_kernelsize()) {
      total_size += 2 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->filters_median_blur_kernelsize());
    }
    
    // required bool filters_Adaptive_threshold = 20;
    if (has_filters_adaptive_threshold()) {
      total_size += 2 + 1;
    }
    
    // required int64 filters_Adaptive_threshold_blockSize = 21;
    if (has_filters_adaptive_threshold_blocksize()) {
      total_size += 2 +
        ::google::protobuf::internal::WireFormatLite::Int64Size(
          this->filters_adaptive_threshold_blocksize());
    }
    
    // required int64 filters_Adaptive_threshold_C = 22;
    if (has_filters_adaptive_threshold_c()) {
      total_size += 2 +
        ::google::protobuf::internal::WireFormatLite::Int64Size(
          this->filters_adaptive_threshold_c());
    }
    
    // required bool filters_Threshold = 23;
    if (has_filters_threshold()) {
      total_size += 2 + 1;
    }
    
    // required int64 filters_Threshold_value = 24;
    if (has_filters_threshold_value()) {
      total_size += 2 +
        ::google::protobuf::internal::WireFormatLite::Int64Size(
          this->filters_threshold_value());
    }
    
  }
  if (_has_bits_[24 / 32] & (0xffu << (24 % 32))) {
    // required bool filters_dilate = 25;
    if (has_filters_dilate()) {
      total_size += 2 + 1;
    }
    
    // required string filters_dilationSize = 26;
    if (has_filters_dilationsize()) {
      total_size += 2 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->filters_dilationsize());
    }
    
    // required bool filters_Canny = 27;
    if (has_filters_canny()) {
      total_size += 2 + 1;
    }
    
    // required int64 filters_Canny_First_Threshold = 28;
    if (has_filters_canny_first_threshold()) {
      total_size += 2 +
        ::google::protobuf::internal::WireFormatLite::Int64Size(
          this->filters_canny_first_threshold());
    }
    
    // required int64 filters_Canny_Second_Threshold = 29;
    if (has_filters_canny_second_threshold()) {
      total_size += 2 +
        ::google::protobuf::internal::WireFormatLite::Int64Size(
          this->filters_canny_second_threshold());
    }
    
    // required string filters_Canny_apertureSize = 30;
    if (has_filters_canny_aperturesize()) {
      total_size += 2 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->filters_canny_aperturesize());
    }
    
  }
  // repeated .SystemSettings.HSV red_instances = 31;
  total_size += 2 * this->red_instances_size();
  for (int i = 0; i < this->red_instances_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->red_instances(i));
  }
  
  // repeated .SystemSettings.HSV blue_instances = 32;
  total_size += 2 * this->blue_instances_size();
  for (int i = 0; i < this->blue_instances_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->blue_instances(i));
  }
  
  // repeated .SystemSettings.HSV green_instances = 33;
  total_size += 2 * this->green_instances_size();
  for (int i = 0; i < this->green_instances_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->green_instances(i));
  }
  
  // repeated .SystemSettings.HSV yellow_instances = 34;
  total_size += 2 * this->yellow_instances_size();
  for (int i = 0; i < this->yellow_instances_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->yellow_instances(i));
  }
  
  // repeated .SystemSettings.HSV violet_instances = 35;
  total_size += 2 * this->violet_instances_size();
  for (int i = 0; i < this->violet_instances_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->violet_instances(i));
  }
  
  // repeated .SystemSettings.HSV cyan_instances = 36;
  total_size += 2 * this->cyan_instances_size();
  for (int i = 0; i < this->cyan_instances_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->cyan_instances(i));
  }
  
  // repeated .SystemSettings.HSV black_instances = 37;
  total_size += 2 * this->black_instances_size();
  for (int i = 0; i < this->black_instances_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->black_instances(i));
  }
  
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void SystemSettings::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const SystemSettings* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const SystemSettings*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void SystemSettings::MergeFrom(const SystemSettings& from) {
  GOOGLE_CHECK_NE(&from, this);
  red_instances_.MergeFrom(from.red_instances_);
  blue_instances_.MergeFrom(from.blue_instances_);
  green_instances_.MergeFrom(from.green_instances_);
  yellow_instances_.MergeFrom(from.yellow_instances_);
  violet_instances_.MergeFrom(from.violet_instances_);
  cyan_instances_.MergeFrom(from.cyan_instances_);
  black_instances_.MergeFrom(from.black_instances_);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_input_edit_camera_setting()) {
      set_input_edit_camera_setting(from.input_edit_camera_setting());
    }
    if (from.has_input_white_balance_blue_u()) {
      set_input_white_balance_blue_u(from.input_white_balance_blue_u());
    }
    if (from.has_input_white_balance_red_v()) {
      set_input_white_balance_red_v(from.input_white_balance_red_v());
    }
    if (from.has_input_exposure()) {
      set_input_exposure(from.input_exposure());
    }
    if (from.has_input_brightness()) {
      set_input_brightness(from.input_brightness());
    }
    if (from.has_input_sharpness()) {
      set_input_sharpness(from.input_sharpness());
    }
    if (from.has_input_gain()) {
      set_input_gain(from.input_gain());
    }
    if (from.has_input_hue()) {
      set_input_hue(from.input_hue());
    }
  }
  if (from._has_bits_[8 / 32] & (0xffu << (8 % 32))) {
    if (from.has_input_sat()) {
      set_input_sat(from.input_sat());
    }
    if (from.has_input_contrast()) {
      set_input_contrast(from.input_contrast());
    }
    if (from.has_input_network_ip()) {
      set_input_network_ip(from.input_network_ip());
    }
    if (from.has_input_network_port()) {
      set_input_network_port(from.input_network_port());
    }
    if (from.has_filters_crop_photo()) {
      set_filters_crop_photo(from.filters_crop_photo());
    }
    if (from.has_filters_crop_firstpoint_x()) {
      set_filters_crop_firstpoint_x(from.filters_crop_firstpoint_x());
    }
    if (from.has_filters_crop_firstpoint_y()) {
      set_filters_crop_firstpoint_y(from.filters_crop_firstpoint_y());
    }
    if (from.has_filters_crop_secondpoint_x()) {
      set_filters_crop_secondpoint_x(from.filters_crop_secondpoint_x());
    }
  }
  if (from._has_bits_[16 / 32] & (0xffu << (16 % 32))) {
    if (from.has_filters_crop_secondpoint_y()) {
      set_filters_crop_secondpoint_y(from.filters_crop_secondpoint_y());
    }
    if (from.has_filters_median_blur()) {
      set_filters_median_blur(from.filters_median_blur());
    }
    if (from.has_filters_median_blur_kernelsize()) {
      set_filters_median_blur_kernelsize(from.filters_median_blur_kernelsize());
    }
    if (from.has_filters_adaptive_threshold()) {
      set_filters_adaptive_threshold(from.filters_adaptive_threshold());
    }
    if (from.has_filters_adaptive_threshold_blocksize()) {
      set_filters_adaptive_threshold_blocksize(from.filters_adaptive_threshold_blocksize());
    }
    if (from.has_filters_adaptive_threshold_c()) {
      set_filters_adaptive_threshold_c(from.filters_adaptive_threshold_c());
    }
    if (from.has_filters_threshold()) {
      set_filters_threshold(from.filters_threshold());
    }
    if (from.has_filters_threshold_value()) {
      set_filters_threshold_value(from.filters_threshold_value());
    }
  }
  if (from._has_bits_[24 / 32] & (0xffu << (24 % 32))) {
    if (from.has_filters_dilate()) {
      set_filters_dilate(from.filters_dilate());
    }
    if (from.has_filters_dilationsize()) {
      set_filters_dilationsize(from.filters_dilationsize());
    }
    if (from.has_filters_canny()) {
      set_filters_canny(from.filters_canny());
    }
    if (from.has_filters_canny_first_threshold()) {
      set_filters_canny_first_threshold(from.filters_canny_first_threshold());
    }
    if (from.has_filters_canny_second_threshold()) {
      set_filters_canny_second_threshold(from.filters_canny_second_threshold());
    }
    if (from.has_filters_canny_aperturesize()) {
      set_filters_canny_aperturesize(from.filters_canny_aperturesize());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void SystemSettings::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void SystemSettings::CopyFrom(const SystemSettings& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool SystemSettings::IsInitialized() const {
  if ((_has_bits_[0] & 0x3fffffff) != 0x3fffffff) return false;
  
  for (int i = 0; i < red_instances_size(); i++) {
    if (!this->red_instances(i).IsInitialized()) return false;
  }
  for (int i = 0; i < blue_instances_size(); i++) {
    if (!this->blue_instances(i).IsInitialized()) return false;
  }
  for (int i = 0; i < green_instances_size(); i++) {
    if (!this->green_instances(i).IsInitialized()) return false;
  }
  for (int i = 0; i < yellow_instances_size(); i++) {
    if (!this->yellow_instances(i).IsInitialized()) return false;
  }
  for (int i = 0; i < violet_instances_size(); i++) {
    if (!this->violet_instances(i).IsInitialized()) return false;
  }
  for (int i = 0; i < cyan_instances_size(); i++) {
    if (!this->cyan_instances(i).IsInitialized()) return false;
  }
  for (int i = 0; i < black_instances_size(); i++) {
    if (!this->black_instances(i).IsInitialized()) return false;
  }
  return true;
}

void SystemSettings::Swap(SystemSettings* other) {
  if (other != this) {
    std::swap(input_edit_camera_setting_, other->input_edit_camera_setting_);
    std::swap(input_white_balance_blue_u_, other->input_white_balance_blue_u_);
    std::swap(input_white_balance_red_v_, other->input_white_balance_red_v_);
    std::swap(input_exposure_, other->input_exposure_);
    std::swap(input_brightness_, other->input_brightness_);
    std::swap(input_sharpness_, other->input_sharpness_);
    std::swap(input_gain_, other->input_gain_);
    std::swap(input_hue_, other->input_hue_);
    std::swap(input_sat_, other->input_sat_);
    std::swap(input_contrast_, other->input_contrast_);
    std::swap(input_network_ip_, other->input_network_ip_);
    std::swap(input_network_port_, other->input_network_port_);
    std::swap(filters_crop_photo_, other->filters_crop_photo_);
    std::swap(filters_crop_firstpoint_x_, other->filters_crop_firstpoint_x_);
    std::swap(filters_crop_firstpoint_y_, other->filters_crop_firstpoint_y_);
    std::swap(filters_crop_secondpoint_x_, other->filters_crop_secondpoint_x_);
    std::swap(filters_crop_secondpoint_y_, other->filters_crop_secondpoint_y_);
    std::swap(filters_median_blur_, other->filters_median_blur_);
    std::swap(filters_median_blur_kernelsize_, other->filters_median_blur_kernelsize_);
    std::swap(filters_adaptive_threshold_, other->filters_adaptive_threshold_);
    std::swap(filters_adaptive_threshold_blocksize_, other->filters_adaptive_threshold_blocksize_);
    std::swap(filters_adaptive_threshold_c_, other->filters_adaptive_threshold_c_);
    std::swap(filters_threshold_, other->filters_threshold_);
    std::swap(filters_threshold_value_, other->filters_threshold_value_);
    std::swap(filters_dilate_, other->filters_dilate_);
    std::swap(filters_dilationsize_, other->filters_dilationsize_);
    std::swap(filters_canny_, other->filters_canny_);
    std::swap(filters_canny_first_threshold_, other->filters_canny_first_threshold_);
    std::swap(filters_canny_second_threshold_, other->filters_canny_second_threshold_);
    std::swap(filters_canny_aperturesize_, other->filters_canny_aperturesize_);
    red_instances_.Swap(&other->red_instances_);
    blue_instances_.Swap(&other->blue_instances_);
    green_instances_.Swap(&other->green_instances_);
    yellow_instances_.Swap(&other->yellow_instances_);
    violet_instances_.Swap(&other->violet_instances_);
    cyan_instances_.Swap(&other->cyan_instances_);
    black_instances_.Swap(&other->black_instances_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    std::swap(_has_bits_[1], other->_has_bits_[1]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata SystemSettings::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = SystemSettings_descriptor_;
  metadata.reflection = SystemSettings_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)
